# https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Docker-Compose
version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 32769
      - "5900:5900" # VPN
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
    depends_on:
      - hub

  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 32770
      - "5901:5900" # VPN
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
    depends_on:
      - hub
